### ISSUE TITLE
:) I was thinking of playing around this idea too

### ISSUE THREAD

**Issue by rajibahmed** [joaomilho/webpack-module-federation-typescript-monorepo#1]
I really like the idea of module federation. 

Curious about -  
How was the developer experience around implementing this ?
Can it be easily implemented for existing webpack5 apps? 

Not are real issue :)

Have a good day sir !

**Comment by joaomilho** [comment]
Hej Rajib,

The DX is real great as each project can totally run on its own.

For existing webpack apps, all you have to do is add the exposes/consumes config.

Now, I feel it's a bit impossible to do all this right without a monorepo, as having one simplifies achieving type safety and have a concise list of consumes/produces in one place.

How is life?

**Comment by rajibahmed** [comment]
Life is a bit less stressful now :) getting paid by hours. Life simpler now :) 
experimenting with hasura and nx (reactnative) on free time. Hasura is nice :) give it a look if you get sometime. 

Is the grass a bit greener and comfortable on the green logo company? :D
